spring.application.name=post-service
server.port=8081

# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/post
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate / JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Optional: Connection pool (HikariCP m?c ??nh)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000